name: pytest

on:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: pre-commit (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install pytest pytest-xdist
          pytest -n auto
